#!/bin/bash

set -e

cd "$(dirname "$0")/.."

export NVM_DIR="$HOME/.nvm"
[ -s "$NVM_DIR/nvm.sh" ] && \. "$NVM_DIR/nvm.sh"  # This loads nvm
[ -s "$NVM_DIR/bash_completion" ] && \. "$NVM_DIR/bash_completion"  # This loads nvm bash_completion

. venv/bin/activate
pip install --upgrade pip
pip install build
nvm use
yarn install
node_modules/.bin/gulp setup-and-fetch-nightly-translations
node_modules/.bin/gulp build-app

# finally pack the release
pip install build
python -m build
